FORMAT: 1A
HOST: http://apix.lingxi360.com/v1
GITHUB_FILE_PATH: http://github.com/rrylee

# 灵析 API 文档(V1)

# Group 开始使用

:::warning
所有的接口请求链接前缀都需要带上版本号 http://apix.lingxi360.com/v1
:::

## 接入说明

:::note
有任何问题请联系官方邮箱 api@justering.com
:::

**调用所有接口，必须包含下面四个参数**

| 字段名称   |  类型  |  说明  |
| -- | -- | :-- |
|  api_key  |  string  |  api_key  |
| stamp   |  int  |  发送请求的时间，UNIX时间戳  |
|  noncestr  |  string  |  随机字符串  |
|  signature  |  string  |  签名  |

**signature 的验证方式**

- 首先验证时间戳是否在当前时间 600s 内
- 其次验证 signature 是否正确

**signature 参数生成步骤**

* 设所有需要发送的数据为集合M，在集合M中增加当前时间戳stamp，随机字符串noncestr以及机构的api_key，然后将集合M内非空参数值（或空数组）的参数按照参数名ASCII码从小到大排序（字典序），使用URL键值对的格式（即key1=value1&key2=value2…）拼接成字符串stringA。
* 对stringA进行sha256哈希计算，秘钥api_secret，得到signature值

**signature 参数验证步骤**

* 设所有接收到的数据为集合M，将集合M内非空参数值（或空数组）的参数按照参数名ASCII码从小到大排序（字典序），使用URL键值对的格式（即key1=value1&key2=value2…）拼接成字符串stringA。
* 对stringA进行sha256哈希计算，秘钥api_secret，得到signature值

**验证和生成签名特别注意以下重要规则**

* 参数名ASCII码从小到大排序（字典序）；
* 如果参数的值为空（或空数组）不参与签名；
* 参数名区分大小写；
* 验证调用返回或微信主动通知签名时，传送的signature参数不参与签名，将生成的签名与该signature参数值作校验。
* 接口可能会增加字段，验证签名时必须支持增加的扩展字段

**获取 api_key 和 api_secret**

灵析系统会为每个灵析账户分配一个api_key和api_secret, 请向灵析技术人员索取

<br/>

## 参数及返回类型说明

:::warning
返回结果都是 unicode 编码
:::

**分页参数**

| 字段名称 | 类型 | 说明 | 默认 |
| :-- | -- |:-- | :-- |
| min_time   |  int  |  资源的最小创建时间，UNIX时间戳  | 默认不参与分页限制 |
|  max_time  |  int  |  资源的最大创建时间，UNIX时间戳  | 默认不参与分页限制 |
|  page  |  int  |  分页页面  | 1 |
|  per_page  |  int  |  分页每页记录条数 | **默认为10, 最大不超过500, 具体参考具体 api** |
| order_by | string | 排序方式 | **参考具体 api** |
| order_sequence | string | 排序方式 | asc, desc 默认为 desc |

:::note
建议手动传入 per_page 来获取分页数据
:::

**with 参数**

使用接口给出的 with 参数获取资源的其他信息

比如

    donate/?with=user,project

表示去获取 donate 的同时带上 user 和 project 信息

**返回数据格式**

> 请求单个数据接口

```json
{
  "data": {
    "type": "event",
    "id": "cam7klxnremov5gydo1019z84pwq237o",
    "attributes": {

    }
  }
}
```

> 统计数据

```json
{
  "data": {
    "total": 1000
  }
}
```

> 分页数据

```json
{
  "meta": {
    "pagination": {
      "total": 171,
      "count": 10,
      "per_page": 10,
      "current_page": 1,
      "total_pages": 18
    }
  },
  "links": {
    "self": "http://apixtest.lingxi360.com/v1/cf_project/list?page=1",
    "first": "http://apixtest.lingxi360.com/v1/cf_project/list?page=1",
    "next": "http://apixtest.lingxi360.com/v1/cf_project/list?page=2",
    "last": "http://apixtest.lingxi360.com/v1/cf_project/list?page=18"
  }
}
```

:::warning
后面文档不做特殊说明，默认只说明 attributes 字段含义
:::

<br/>

## SDK 地址

_如何下载安装，具体参考链接文档_

- php [链接](https://github.com/LingxiTeam/api-authentication)

- node [链接](https://github.com/RryLee/node-signature-authenticator)

# Data Structures

# Group 测试接口

:::note
不需要任何验证参数，不产生请求记录
:::

## 测试调用接口 [/test/fun]

### 测试调用接口 [GET]

+ Response 200

  + Body

            {
              "msg": "Hello, Lingxi!!!"
            }

## 测试参数验证 [/test/auth]

### 测试参数验证 [GET]

+ Response 200

  + Body

            {
              "stamp": "1482473936",
              "noncestr": "7wXXaVTcRtz6DydF",
              "api_key": "pj5iHdpka",
              "signature": "33ef3dc5fb9d74e9c89caea91123bb5705f8e8e9f2823ba7525405cd88e08002"
            }

# Data Structures

# Group 联系人

## 获取单个联系人 [/contact/show]

### 单个联系人 [GET]

| 名称   | 类型 |  必填  |  说明  |
| :-- | :--: | :--: | :-- |
|  cid  | string |  &#10007;  |  联系人 id  |
|  wechat_openid | string  |  &#10007;  |  联系人微信 openid，和 cid 两者必传一个  |
|  with  | string |  &#10007;  |  企业-`org`, 附件-`attachments`, 活动统计-`statistics_event`, 捐款统计-`statistics_donate` |

+ Response 200

  + Body

            {
              "name": "京城五", // (string) 姓名
              "nickname": "", // (string) 名称
              "email": "guorunmiao@qq.com", // (string) 邮箱
              "email2": "", // (string) 备用邮箱
              "mobile": "12323234545", // (string) 手机号
              "mobile2": "", // (string) 备用手机号
              "birthday": "0000-00-00", // (string) 生日
              "gender": "", // (string) 性别
              "avatar": "http://wx.qlogo.cn/mmopen/ajNVdqHZLLADwPUGnaAmvzHu3R4sK33OUJnLdqd97GHn2fgjiaiaKvrXs78oYUuFziahlOSCygj1z696I4ian9CACQ/0", // (string) 图像
              "address": "三元桥", // (string) 地址
              "zip_code": "", // (string) 邮编
              "description": "", // (string)
              "org_id": 102666,
              "org_department": "", // (string) 工作单位部门
              "org_position": "", // (string) 单位地址
              "org_phone": "", // (string) 单位电话
              "country": "", // (string) 国家
              "province": "", // (string) 省份
              "qq": "28223123", // (string) qq
              "wx_username": "", // (string) 微信用户名
              "weibo_name": "", // (string) 微博名称
              "weibo_link": "", // (string) 微博链接
              "create_time": 1403447755, // (int) 创建时间
              "update_time": 1427448819, // (int) 更新时间
              "constellation": 0, // (int) 星座
              "member": "", // (string)
              "member_donate_count": 0, // (int)
              "member_donate_sum": 0, // (int)
              "member_donate_first_date": 0, // (int)
              "member_credit_score": 0, // (int)
              "org": { // 单位详细信息
                "id": "cavl1l5m4zq97xwn0wz023ye8pvrkogz", // (string)
                "name": "灵析", // (string)
                "website": "http://www.lingxi360.com/index.php", // (string) 网站
                "logo": "", // (string)
                "phone": "010-4683670", // (string)
                "fax": "010-64683671", // (string)
                "address": "远洋新干线A座1109", // (string)
                "zipcode": "10027", // (string)
                "email": "hi@lingxi.com", // (string)
                "description": "欢迎大家拍砖、献花和我们约聊······这里是十分热情的灵析团队！", // (string)
                "contact_user": "易昕", // (string) 单位联系人
                "create_time": 1460638709 // (int) 创建时间
              },
              "statistics_event": { // 活动统计
                "count_event": 7, // (int) 活动次数
                "duration": 16 // (int) 活动时间
              },
              "statistics_donate": { // 捐款统计
                "count_paid": 1, // (int) 支付次数
                "sum_paid": "25.00" // (float) 联系人捐款总数
              }
            }

## 获取联系人参与全部项目 [/contact/cf_project/list]

### 参与全部项目 [GET]

| 名称   | 类型 |  必填  |  说明  |
| :-- | :--: | :--: | :-- |
|  cid  | string | &#10004;  |  联系人 id  |
|  type | string | &#10007; | 项目类型 单次捐-`singletime` 定期捐-`periodic` |
|  category_id | string | &#10007; | 分类 id |
|  order_by | string | &#10007; | 我的捐赠-`sum_paid` `create_time` `update_time` |
|  with  | string |  &#10007;  |  我的捐赠-`donates` 统计信息-`statistics_donate` 其他信息-`components` |

+ Response 200

  + Body


            {
              "type": "singletime", // (string) singletime(单次捐), periodic(定期捐)
              "team_id": "ca7nxo5qvzl9gm10q2vk07w3rp24e8yk", // (string)
              "cid": "ca17nxo5qvzl9gm10q507w3rp24e8ykw", // (string) 项目分类 id
              "title": "七夕，给你一个爱的约会", // (string) 标题
              "summary": "", // (string) 简介
              "desc": "<p><span style=\"font-family: 微软雅黑, 'Microsoft YaHei'; line-height: 1.5em;\">嗨，[#姓名#]<br></span></p>", // (string) 详细
              "sequence": "0", // (string) 权重
              "preview_image": "http://file.lxi.me//attachment/2015/0915/4cf0c61a6aa6b26b3e48a17205c44a14.jpg", // (string) 预览图片
              "is_special": true, // (bool) 是否顶置
              "status": "published", (string) published(发布),  closed(关闭), draft(草稿)
              "goal": false, // (bool) 是否有目标
              "is_donatable": true, // (bool) 是否可以捐赠
              "is_together_donatable": false, // (bool) 是否开启团队捐
              "create_time": 1442032723, // (string) 创建时间
              "update_time": 1444878789, // (string) 更新时间
              "sum_paid": 8.74, // (float) 项目总筹款款
              "count_user_paid": "10", // (float) 捐款人数
              "components": {
                "periodic": { // 定期捐信息
                  "information": {
                    "is_enabled": "1", // (string) 是否开启分档筹款
                    "options": [
                      {
                        "money": "6", // (string) 额度
                        "desc": "一个羊肉串",
                        "limit_num": "100"
                      },
                      {
                        "money": "8",
                        "desc": "一串鸡翅",
                        "limit_num": "100"
                      },
                      {
                        "money": "60",
                        "desc": "一个靠羊腿",
                        "limit_num": "100"
                      }
                    ],
                    "is_input_allowed": "false" // 是否允许用户自己输入额度
                  }
                },
                "donate_certificate": { // 项目每次捐赠证书配置
                  "config": {
                    "is_enable": "0",
                    "cert_template_id": "carp7vl4kq13904we81ez6m2yxoez5wg" // (string) 证书 id
                  }
                },
                "project_donate_certificate": { // 项目级别证书
                  "config": {
                    "is_enable": "0",
                    "cert_template_id": "carp7vl4kq13904we81ez6m2yxoez5wg"
                  }
                },
                "goal": { // 项目目标
                  "is_enable": false, // (bool) 是否开启
                  "is_enable_achieved_donate": false, // (bool) 达到目标是否可以继续捐赠
                  "goal_num": 0 // 目标金额
                },
                "expire": { // 项目到期时间
                  "is_enable": false, // (bool) 是否开启
                  "expire_time": 0 // (int) 过期时间
                },
                "success_number_limit": { // 捐赠次数上限
                  "is_enable": false, // (bool) 是否开启
                  "limit_num": 0 // (int) 次数限制
                }
              }，
              "link": "http://cf.lingxi360.com/p/ca512p4q3yewvdk5y3qgodzgl8mknx7r", // 项目链接
              "donates": [ // 和捐赠信息一致
                {
                  "id": "carp7vl4kq13904we81ez6m2yxoez5wg",
                  "user_project_id": "caox9g48omp21rydmrwn6vew7n5qkz3l",
                  "project_id": "ca512p4q3yewvdk5y3qgodzgl8mknx7r",
                  "cf_user_id": "canxo5qvzl9gm10qp9lkld7w3rp24e8y",
                  "donate_cf_user_id": "canxo5qvzl9gm10qp9lkld7w3rp24e8y",
                  "contact_id": "capx8v2gr3ymw40557mp309qo571ezkl",
                  "donate_amount": "75.00",
                  "flow_number": "4008632001201608090925588822",
                  "status": "paid",
                  "pay_time": 1470714270,
                  "comment": "",
                  "donate_form_data": {
                    "name": "西桐",
                    "email": "joy_song@126.com",
                    "new_item_1": "",
                    "ip": "10.158.26.1",
                    "browser_user_agent": "Mozilla/5.0 (iPhone; CPU iPhone OS 9_3_3 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Mobile/13G34 MicroMessenger/6.3.23 NetType/4G Language/zh_CN",
                    "browser_referer": "http://cf.lingxi360.com/up/caox9g48omp21rydmrwn6vew7n5qkz3l?ouid=canxo5qvzl9gm10qp9lkld7w3rp24e8y&from=groupmessage&isappinstalled=0"
                  },
                  "create_time": 1470714252,
                  "update_time": 1470714270
                }
              ],
              "statistics_donate": { // 捐赠统计
                "sum": 602.6, // (float) 总筹款额(包括额外捐赠)
                "sum_paid": 600, // (float) 总筹款额(不包括额外捐赠)
                "count": 8, // (int) 总捐款次数(包括额外次数)
                "count_paid": 8, // (int) 总付款次数
                "count_user": 1, // (int) 总捐款人数
                "count_user_paid": 1, // (int) 总捐款人数(包括额外次数)
                "percent": 0, // (int) 项目进度(不超过100)
                "percent_round": 0, // (int) 项目绝对进度(可以超过 100)
                "is_achieved": false, // (bool) 是否达到目标
                "is_expired": true, // (bool) 是否到期
                "is_over_limit": false, // (bool) 是否超出目标
                "is_donatable": false // (bool) 是否可以继续捐赠
              }
            }

## 获取联系人参加的单个项目 [/contact/cf_project/show]

### 参与单个项目信息 [GET]

| 名称   | 类型 |  必填  |  说明  |
| :-- | :--: | :--: | :-- |
|  id  | string | &#10007;  |  项目 id  |
| cid  | string | &#10007; | 联系人 id |
|  with  | string |  &#10007;  |  项目捐赠统计-`statistics_donate` 项目额外信息-`components` 我的捐赠-`donates` |

+ Response 200

```bash
信息同上
```

## 获取联系人参加的全部定期捐 [/contact/cf_project/periodic_project/list]

### 参与定期捐 [GET]

| 名称   | 类型 |  必填  |  说明  |
| :-- | :--: | :--: | :-- |
|  cid  | string | &#10007;  |  联系人 id  |
| wechat_openid | string | &#10007; | 联系人微信 openid (和 cid 必填一项) |
|  status | string | &#10007; | 状态 初始化-`inti` 绑定-`binded` 未绑定-`unbind` |
|  with  | string | &#10007;  |  我的捐赠-`donates` 绑定项目-`project` |

+ Response 200

  + Body


            {
              "project_id": "caz9x45erm3o21kp0g108q9ygw7lvnz2", // (string) 关联项目 id
              "interval": "monthly", // (string) 类型, monthly(月捐), weekly(周捐), daily(日捐)
              "donate_amount": "100.00", // (float) 金额
              "status": "binded", // (string) 状态, binded(绑定), unbinded(解绑), init(初始化)
              "is_anonymous": false, // (bool) 是否匿名
              "bind_time": 1462982400, // (int) 绑定时间
              "next_pay_time": 0, // (int) 下次扣款时间
              "create_time": 1468495900,
              "update_time": 1468495903,
              "comment": "", // (string) 评论
              "manage_link": "http://cfnew.lingxi.com/periodic/caz9x45erm3o21kp0g108q9ygw7lvnz2", // (string) 管理链接
              "donates": [ // (array)
                  {
                      "id": "camrp4nyx9v1wdy321g4v6gzloqk783e",
                      "project_id": "ca924lkpryz7m38qd97x09vxe2n15wog",
                      "cf_user_id": "caqox9g48omp21rydmpdvew7n5qkz3lm",
                      "user_project_id": "ca17nxo5qvzl9gm10q507w3rp24e8ykw",
                      "contact_id": "canrp7vl4kq13904lp8vdm2yxoez5wg8",
                      "donate_amount": 1.01, // (float) 支付金额
                      "flow_number": "k1nrp7vl4kq13904lp8vdm2yxoez5wg8", // (string) 微信，支付宝订单流水号
                      "status": "paid", // (string) 已支付-`paid`, 未支付-`unpaid`
                      "pay_time": 0, // (int) 付款时间
                      "donate_cf_user_id": "caqox9g48omp21rydmpdvew7n5qkz3lm", // (string) 筹款用户 id
                      "comment": "", // (string) 留言
                      "create_time": 1442064826,
                      "update_time": 1442064826
                  }
              ],
              "project": { // 同项目字段
                  "id": "caz9x45erm3o21kp0g108q9ygw7lvnz2",
                  "type": "periodic",
                  "title": "清华大学新百年基金",
                  "summary": "“集资、集智、集力、集心”",
                  "desc": "<p>This is a demo project!!!</p>",
                  "preview_image": "http://file.lxi.me/cf/20160513/5735421ae707e.jpg",
                  "sequence": 24,
                  "status": "published",
                  "create_time": 1438845474,
                  "update_time": 1470294646,
                  "link": "http://cfnew.lingxi.com/p/caz9x45erm3o21kp0g108q9ygw7lvnz2"
              }
            }

## 统计定期捐 [/contact/cf_project/periodic_project/statistics]

### 统计定期捐 [GET]

| 名称   | 类型 |  必填  |  说明  |
| :-- | :--: | :--: | :-- |
|  cid | string |  &#10007;  |  联系人 id  |
| wechat_openid | string | &#10007; | 联系人微信 openid (和 cid 必填一项) |

+ Response 200

  + Body

            {
              "count_join": 2, // (int) 加入的定期捐个数
              "count_paid": 3, // (int) 定期捐扣款次数
              "sum_paid": 7.10 // (float) 扣款金额
            }

## 获取团队捐，我参与和发起的 [/contact/cf_project/user_project/list]

### 获取团队捐 [GET]

| 名称   | 类型 |  必填  |  说明  |
| :-- | :--: | :--: | :-- |
| cid  | string | &#10004;  |  联系人 id  |
| mine | int | &#10007; | 传入 1 表示获取我发起的团队捐 |
| with | string | &#10007; | `donates`, `project`, `statistics_donate` |

+ Response 200

  + Body

            {
              "project_id": "cawn9v23wqo8z7m0n8w80kl5eg4py1rx", // (string) 项目 id
              "goal": "2000.00", // (string) 目标金额
              "title": "交大零八届三班", // (string) 团队标题
              "comment": "匆匆岁月，我们一起奋斗一起长大。饮水思源、助力母校，让更多的师弟师妹茁长成长。", // (string) 团队描述
              "update_time": 1442570268,
              "create_time": 1442570268,
              "project": { // 同项目
                  "id": "cawn9v23wqo8z7m0n8w80kl5eg4py1rx",
                  "type": "singletime",
                  "title": "一起捐定额筹款",
                  "summary": "这里是项目简介",
                  "desc": "<p style=\"margin-top: 0px; margin-bottom: 10px; color: rgb(34, 34, 34); font-family: 'Helvetica Neue', Arial, 'Microsoft Yahei', arial, sans-serif; font-size: 13px; line-height: 20px; white-space: normal; \">\n    <strong>关于项目</strong>\n</p>\n<p style=\"margin-top: 0px; margin-bottom: 10px; color: rgb(34, 34, 34); font-family: 'Helvetica Neue', Arial, 'Microsoft Yahei', arial, sans-serif; font-size: 13px; line-height: 20px; white-space: normal;\">\n    （简短介绍项目详情，让支持者能够在最短时间内了解你的项目）\n</p>",
                  "preview_image": "/uploads/cf_default/cf_demo_project_img.jpg",
                  "sequence": 0,
                  "status": "published",
                  "create_time": 1456976008,
                  "update_time": 1463654233,
                  "link": "http://cfnew.lingxi.com/p/cawn9v23wqo8z7m0n8w80kl5eg4py1rx"
              },
              "donates": [ // (array) 同捐赠
                {
                  "id": "ca94ygk2w7p3n0z5zx93z085m1rxoveq",
                  "project_id": "ca924lkpryz7m38qd97x09vxe2n15wog",
                  "cf_user_id": "caqox9g48omp21rydmpdvew7n5qkz3lm",
                  "user_project_id": "ca4k18e2n3gk9rz70lkgdwoymvl45xqp",
                  "contact_id": "caqox9g48omp21rydmpdvew7n5qkz3lm",
                  "donate_amount": "20.00",
                  "flow_number": "",
                  "status": "paid",
                  "pay_time": 0,
                  "donate_cf_user_id": "caqox9g48omp21rydmpdvew7n5qkz3lm",
                  "comment": "",
                  "create_time": 1442065196,
                  "update_time": 1442065196
                }
              ]
            }

## 统计团队捐 [/contact/cf_project/user_project/statistics]

## 统计团队捐 [GET]

| 名称   | 类型 |  必填  |  说明  |
| :-- | :--: | :--: | :-- |
| cid | string |  &#10004;  |  联系人 id  |
| me | int | &#10007; | 传入 1 表示获取我参与的团队捐 |
| mine | int | &#10007; | 我发起的定期捐 (me, mine 两个参数最少传 1 个) |

+ Response 200

  + Body


            {
              "mine": {
                "count_create_user_project": 8, // (int) 创建的团队捐个数
                "count_user_paid": 2, // (int) 独立用户参与人数
                "sum_paid": "33905.74" // (int) 已筹金额
              },
              "me": {
                "count_donate_user_project": 58, // (int) 捐赠的团队捐个数
                "sum_paid": 128072.35 // (float) 个人参与团队捐捐赠金额
              }
            }

## 获取填写的表单列表 [/contact/form/list]

### 获取填写的表单列表 [GET]

| 名称   | 类型 |  必填  |  说明  |
| :-- | :--: | :--: | :-- |
| cid  | string | &#10004;  |  联系人 id  |
| order_by  | string | &#10007;  |  `id` `sequence` `create_time` `update_time`  |
| with | string | &#10007; | 统计-`statistics_form`, 我的填写-`form_fills` |

+ Response 200

  + Body


            {
              "title": "基本的功能完成了0", // (string) 表单标题
              "summary": "还要再增加一个备注\r\n感谢您在百忙之中抽出时间填写问卷，我们将在答卷中抽取幸运用户送上精美小礼品一份！\r\n备注可以得修改名称备注可以得修改名称！\r\n", // (string) 表单描述
              "status": "published", // (string) 状态
              "start_time": 0, // (int) 开始时间
              "end_time": 0, // (int) 结束时间
              "create_time": 1394364652,
              "update_time": 1395390441,
              "sequence": 0, // (int) 权重
              "statistics_form": { // 表单统计
                  "form_id": "cavlypqrolg7zwk463z0v8xem3295n1x",
                  "count_fill": 26 // (int) 填写数量
              },
              "link": "http://f.lingxi360.com/f/?token=KDR0cl4Gz7RyhDOhhkImP_ENi", // (string) 表单链接
              "form_fills": [ // 我的表单填写数据
                  {
                      "id": "cam7klxnremov5gydo1019z84pwq237o",
                      "data": { // 填写内容
                          "name": "郭润苗",
                          "mobile": "13426422862",
                          "email": "guorunmiao@qq.com",
                          "province": "辽宁",
                          "note": "18d95846d271ab3e8915445951db3918",
                          "form_token": "abff503089dcb657f76a4aa04a40af33"
                      },
                      "create_time": 1395039403 // (int) 填写时间
                  }
              ]
            }

## 查找 wechat_openid [/contact/query/wechat_openid]

### 查找 wechat_openid [GET]

| 名称   | 类型 |  必填  |  说明  |
| :-- | :--: | :--: | :-- |
| cid  | string | &#10004;  |  联系人 id  |

+ Response 200

  + Body


            {
              "wechat_openid": "o22Yxtw0NnD69pUhKRKFMhgcU8lY" // (string)
            }

## 查找 cid [/contact/query/cid]

### 查找 cid [GET]

| 名称   | 类型 |  必填  |  说明  |
| :-- | :--: | :--: | :-- |
| wechat_openid  | string | &#10004;  |  微信 openid  |

+ Response 200

  + Body


            {
              "cid": "ca2lo512p4q3yewvdkevdzgl8mknx7r9" // (string)
            }

# Data Structures

# Group 活动

## 活动列表 [/event/list]

### 活动列表 [GET]

| 名称   | 类型 |  必填  |  说明  |
| :-- | :--: | :--: | :-- |
| cid  | string | &#10004;  |  联系人 id  |
| type_id  | string | &#10007;  |  活动类型 id  |
| order_by | string | &#10007; | `id`, `update_time`, `create_time` |
| with |  string | &#10007; | 活动附件-`attachments`, 用户参与活动的信息-`info`(需要传 `cid` 时才生效) |

+ Response 200

  + Body


            {
              "contact_user": "Rry", // (string) 活动创建人名称
              "title": "故宫一日游", // (string) 活动名称
              "type_id": "cam1nrp7vl4kq1396490m2yxoez5wg8w", // (string) 活动分类 id
              "description": "", // (string) 活动说明
              "image": "", // (string) 活动图片
              "event_time": 0, // (int) 管理员自己写的活动开始时间
              "event_duration": 0, // (int) 活动时长
              "relate_link": "", // (string) 活动关联链接
              "create_time": 1465963851,
              "update_time": 1465963851,
              "attachments": [ // (array) 附件
                  {
                    "path": "http://file.lxi.me/page/2014/0829/79dd0e0fb11881562fbbdca807980bc213084652.jpg", // (string) 路径
                    "ext": "jpg", // (string) 文件后缀
                    "mimetype": "image/jpeg", // (string) 文件类型
                    "size": 48728 // (int) 大小
                  },
                  {
                    "path": "http://file.lxi.me/attachment/2015/0627/a6158a1276dbb246e258ab37ce98f3a6.docx",
                    "ext": "docx",
                    "mimetype": "application/octet-stream",
                    "size": 19645
                  }
              },
              "info": { // 有 cid 同时 with 了 info 才会查询出现
                "id": "cam1nrp7vl4kq1396490m2yxoez5wg8w",
                "event_id": "cam1nrp7vl4kq1396490m2yxoez5wg8w", // (string) 活动 id
                "contact_id": "cam1nrp7vl4kq1396490m2yxoez5wg8w", // (string) 联系人 id
                "create_time": 1465963850, // (int) 联系人加入活动时间
                "duration": 8, // (int) 联系人参与时间
                "score": 2 // (int) 参与这次活动积分
              }
            }

## 单个活动信息 [/event/show]

### 单个活动信息 [GET]

| 名称   | 类型 |  必填  |  说明  |
| :-- | :--: | :--: | :-- |
| id  | string |  &#10004;  |  活动 id  |
| with | string | &#10007; | 活动附件-`attachments` |

+ Response 200

  + Body

            { // 同上列表内容
              "contact_user": "易昕",
              "title": "灵犀产品讨论日0",
              "type_id": "ca17nxo5qvzl9gm10q507w3rp24e8ykw",
              "description": "下午2:00开始，进行灵犀产品使用讨论。预计到7:00结束。",
              "image": "",
              "event_time": 0,
              "event_duration": 0,
              "relate_link": "",
              "create_time": 1370505243,
              "update_time": 1370505243,
              "attachments": [
                  {
                  "path": "http://file.lxi.me/page/2014/0829/79dd0e0fb11881562fbbdca807980bc213084652.jpg",
                  "ext": "jpg",
                  "mimetype": "image/jpeg",
                  "size": 48728
                  }
              ]
            }

# Data Structures

# Group 捐赠项目

## 捐赠项目列表 [/cf_project/list]

### 捐赠项目列表 [GET]

| 名称   | 类型 |  必填  |  说明  |
| :-- | :--: | :--: | :-- |
| category_id | string | &#10007; | 分类 id |
| status | string | &#10007; | 项目状态 草稿-`draft` 已发布-`published` 已关闭-`closed` |
| type | string | &#10007; | 项目类型 单次捐-`singletime` 定期捐-`periodic` |
| is_special | int | &#10007; | 是否置顶 0, 1 |
| order_by | string | &#10007; | `sum_paid`, `count_user_paid`, `create_time`, `update_time` |
| with  | string |  &#10007;  |  统计信息-`statistics_donate` 其他信息-`components`  |

+ Response 200

  + Body

            {
              "type": "singletime", // (string) 类型 singletime - periodic
              "cid": "ca17nxo5qvzl9gm10q507w3rp24e8ykw", // (string) 分类 id
              "title": "撸串众筹", // (string) 标题
              "summary": "", // (string) 口号
              "desc": "<p><span style=\"font-family: 微软雅黑, 'Microsoft YaHei'; line-height: 18px;\">testtest</span></p>", // (string) 描述
              "is_special": false, // (string) 是否置顶
              "preview_image": "/attachment/2015/0915/4cf0c61a6aa6b26b3e48a17205c44a14.jpg", // (string) 预览图
              "sequence": 0, // (string) 排序
              "status": "published", // (string) 状态 `published` - `closed` - `draft`
              "create_time": 1442032723,
              "update_time": 1463717527,
              "sum_paid": 0.01, // (float) 目前捐款
              "count_user_paid": 0, // (int) 目前捐款人次
              "components": {
                "periodic": { // 定期捐信息
                  "information": {
                    "is_enabled": "1", // (string) 是否开启分档筹款
                    "options": [
                      {
                        "money": "6", // (string) 额度
                        "desc": "一个羊肉串",
                        "limit_num": "100"
                      },
                      {
                        "money": "8",
                        "desc": "一串鸡翅",
                        "limit_num": "100"
                      },
                      {
                        "money": "60",
                        "desc": "一个靠羊腿",
                        "limit_num": "100"
                      }
                    ],
                    "is_input_allowed": "false" // 是否允许用户自己输入额度
                  }
                },
                "donate_certificate": { // 项目每次捐赠证书配置
                  "config": {
                    "is_enable": "0",
                    "cert_template_id": "0"
                  }
                },
                "project_donate_certificate": { // 项目级别证书
                  "config": {
                    "is_enable": "0",
                    "cert_template_id": "0"
                  }
                },
                "goal": { // 项目目标
                  "is_enable": false, // (bool) 是否开启
                  "is_enable_achieved_donate": false, // (bool) 达到目标是否可以继续捐赠
                  "goal_num": 0 // 目标金额
                },
                "expire": { // 项目到期时间
                  "is_enable": false, // (bool) 是否开启
                  "expire_time": 0 // (int) 过期时间
                },
                "success_number_limit": { // 捐赠次数上限
                  "is_enable": false, // (bool) 是否开启
                  "limit_num": 0 // (int) 次数限制
                }
              },
              "statistics_donate": {
                "sum": 602.6, // (float) 总筹款额(包括额外捐赠)
                "sum_paid": 600, // (float) 总筹款额(不包括额外捐赠)
                "count": 8, // (int) 总捐款次数(包括额外次数)
                "count_paid": 8, // (int) 总付款次数
                "count_user": 1, // (int) 总捐款人数
                "count_user_paid": 1, // (int) 总捐款人数(包括额外次数)
                "percent": 0, // (int) 项目进度(不超过100)
                "percent_round": 0, // (int) 项目绝对进度(可以超过 100)
                "is_achieved": false, // (bool) 是否达到目标
                "is_expired": true, // (bool) 是否到期
                "is_over_limit": false, // (bool) 是否超出目标
                "is_donatable": false // (bool) 是否可以继续捐赠
              }
              "link": "http://cfnew.lingxi.com/p/cam1nrp7vl4kq1396490m2yxoez5wg8w" // 项目链接
            }

## 获取单个项目 [/cf_project/show]

### 获取单个项目 [GET]

| 名称   | 类型 |  必填  |  说明  |
| :-- | :--: | :--: | :-- |
| id  | string | &#10004;  |  项目 id  |
| with | string | &#10007; | 不需要任何 with, 默认给出信息 |

+ Response

```bash
同列表接口
```

## 获取项目留言列表 [/cf_project/comment/list]

### 获取项目留言列表 [GET]

| 名称   | 类型 |  必填  |  说明  |
| :-- | :--: | :--: | :-- |
| pid  | string | &#10004;  |  项目 id  |
| status | string | &#10007; | 留言状态 发布-`published` 草稿-`draft` |
| order_by | string | &#10007; | `create_time`, `sequence` |
| with | string | &#10007; | 留言用户信息-`user` 回复信息-`replys` 点赞信息-`likes` |

+ Response

  + Body


            {
              "cf_user_id": "caqox9g48omp21rydmpdvew7n5qkz3lm", // (string) 留言用户 id
              "comment": "999", // (string) 留言内容
              "sequence": 3, // (int) 排序权重
              "status": "published", // (string) 状态 发布-`published` 草稿-`draft`
              "is_anonymous": true, // (float) 是否匿名
              "create_time": 1465884702,
              "update_time": 1465884702,
              "replys": [ // 回复
                {
                  "id": "ca4k18e2n3gk9rz76lok6woymvl45xqp",
                  "cf_user_id": "cawek7zx2eqwovy9027pd483gmnp5rl1",
                  "comment": "来来来",
                  "sequence": 0,
                  "status": "published",
                  "is_anonymous": false,
                  "create_time": 1469263656,
                  "update_time": 1469263656,
                  "user": {
                    // 回复用户信息
                  }
                }
              ],
              "count_like": 1, // 点赞数量
              "user": { // 留言用户信息
                "team_id": "ca4k18e2n3gk9rz76l7dwoymvl45xqpl",
                "type": "wechat",
                "openid": "o22Yxt3ey8oNo-0YTDTN3gxYogKQ", // 微信 openid
                "user_info": {
                  "openid": "o22Yxt3ey8oNo-0YTDTN3gxYogKQ",
                  "nickname": "Caspar",
                  "sex": 1,
                  "language": "zh_CN",
                  "city": "朝阳",
                  "province": "北京",
                  "country": "中国",
                  "headimgurl": "http://wx.qlogo.cn/mmopen/A83vHGXtO64oO1O8vicOdicDg3NDBoEWia0qYtM3A3U5B7szj6ucetZ1lZV12uoOb9ZsApgFK5bmfrKupLz0IM5bib6mVTmr8l90/0",
                  "privilege": []
                },
                "mobile": "17710189761",
                "contact_id": "ca1gk45nrwzxl30vw3po6vp7e8q29omy",
                "update_time": 1440390574,
                "create_time": 1438491910
              },
              "likes": [ // 点赞信息列表
                {
                  "cf_user_id": "caqox9g48omp21rydmpdvew7n5qkz3lm", // (string)
                  "project_id": "caz9x45erm3o21kp0g108q9ygw7lvnz2", // (string)
                  "comment_id": "caqox9g48omp21rydm520vew7n5qkz3l", // (string)
                  "update_time": 1468816012,
                  "create_time": 1468816012
                }
              ]
            }

## 获取单条留言 [/cf_project/comment/show]

### 获取单条留言 [GET]

| 名称   | 类型 |  必填  |  说明  |
| :-- | :--: | :--: | :-- |
| id  | string | &#10004;  |  留言 id  |
| with | string | &#10007; | 留言用户信息-`user` 回复信息-`replys` 点赞信息-`likes` |

+ Response

```bash
同列表接口
```

## 获取项目捐赠列表 [/cf_project/donate/list]

### 获取项目捐赠列表 [GET]

| 名称   | 类型 |  必填  |  说明  |
| :-- | :--: | :--: | :-- |
| pid  | string | &#10004;  |  项目 id  |
| cid | string | &#10007; | 联系人 id |
| status | string | &#10007; | 支付状态 已支付-`paid` 未支付-`unpaid` |
| order_by | string | &#10007; | donate_amount create_time pay_time |
| with | string | &#10007; | 捐赠用户信息-`user` |

+ Response

  + Body


          {
            "project_id": "caz9x45erm3o21kp0g108q9ygw7lvnz2", // (string) 项目 id
            "cf_user_id": "caqox9g48omp21rydmpdvew7n5qkz3lm", // (string) 项目创建人 id
            "user_project_id": "ca17nxo5qvzl9gm10q507w3rp24e8ykw", // (string) 团队捐项目 id
            "contact_id": "capyw3m54kreo807w8ok692vnxglzq71", // (string) 联系人 id
            "donate_amount": 1000.01, // (float) 捐款额
            "flow_number": "1006930077201509180918911789", // (string) 支付宝，微信流水号
            "status": "paid", // (string) 状态
            "pay_time": 1442571809, // (int) 支付时间
            "donate_cf_user_id": "caqox9g48omp21rydmpdvew7n5qkz3lm", // (string) 捐款人 id
            "comment": "", // (string) 捐款留言
            "create_time": 1442571788,
            "update_time": 1442571788,
            "donate_form_data": {
              "name": "薛藤",
              "mobile": "15510579256",
              "email": "xueteng@justering.com"
            },
            "user": { // 用户信息
                "team_id": "ca4k18e2n3gk9rz76l7dwoymvl45xqpl",
                "type": "wechat",
                "openid": "o22Yxt3ey8oNo-0YTDTN3gxYogKQ",
                "user_info": {
                  "openid": "o22Yxt3ey8oNo-0YTDTN3gxYogKQ",
                  "nickname": "Caspar",
                  "sex": 1,
                  "language": "zh_CN",
                  "city": "朝阳",
                  "province": "北京",
                  "country": "中国",
                  "headimgurl": "http://wx.qlogo.cn/mmopen/A83vHGXtO64oO1O8vicOdicDg3NDBoEWia0qYtM3A3U5B7szj6ucetZ1lZV12uoOb9ZsApgFK5bmfrKupLz0IM5bib6mVTmr8l90/0",
                  "privilege": []
                },
                "mobile": "17710189761",
                "contact_id": "ca1gk45nrwzxl30vw3po6vp7e8q29omy",
                "update_time": 1440390574,
                "create_time": 1438491910
            }
          }

## 获取项目单条捐款信息 [/cf_project/donate/show]

### 获取项目单条捐款信息 [GET]

| 名称   | 类型 |  必填  |  说明  |
| :-- | :--: | :--: | :-- |
| id  | string | &#10004;  |  捐款 id  |
| with | string | &#10007; | 捐赠用户信息-`user` |

+ Response

```bash
同列表
```

## 获取项目进度列表 [/cf_project/progress/list]

### 获取项目进度列表 [GET]

| 名称   | 类型 |  必填  |  说明  |
| :-- | :--: | :--: | :-- |
| pid  | string | &#10004;  |  项目 id  |
| with | string | &#10007; | `project` |

+ Response

  + Body


            {
              "project_id": "caz9x45erm3o21kp0g108q9ygw7lvnz2", // (string) 项目 id
              "title": "Nam magni voluptatibus aut aut quas molestiae et.", // (string) 进度标题
              "desc": "Laudantium sunt sint ut eaque autem. Architecto aut est aperiam. Accusamus iusto molestiae voluptate eos soluta et dicta eum. Eum et est est blanditiis deserunt sed aspernatur. Facilis magni ut occaecati vero.", // (string) 进度描述
              "image": [ // (array) 进度图片
                  {
                      "path": "http:\\/\\/file.lxi.me\\/uploadify\\/20160503\\/57281c13efc20.jpg"
                  }
              ],
              "progress_time": "2016-08-30 18:23:59", // (string) 进度时间
              "create_time": 1472552639,
              "update_time": 1472552639,
              "project": {...} // 同项目字段
            }

### 获取项目分类 [/cf_project/category/list]

### 获取项目分类 [GET]

+ Response

  + Body


            [
              {
                "type": "category",
                "id": "ca924lkpryz7m38q09x09vxe2n15wog4",
                "attributes": {
                  "name": "学院发展基金筹款项目", // (string) 分类标题
                  "create_time": 1464624000,
                  "update_time": 1464624000
                }
              }
            ]

# Data Structures

# Group 表单

## 获取表单列表 [/form/list]

## 获取表单列表 [GET]

| 名称   | 类型 |  必填  |  说明  |
| :-- | :--: | :--: | :-- |
| category_id  | string | &#10007;  |  分类 id  |
| status | string | &#10007;  | 草稿-`draft` 发布-`published` |
| order_by  | string | &#10007;  |  `id` `sequence` `create_time` `update_time`  |

+ Response

  + Body
            {
              "type": "form",
              "id": "ca9r4x83g5ep9wn6rn7g0mlo1qyzv27k",
              "attributes": {
                "title": "扫我啊", // (string) 标题
                "summary": "<p><img src=\"http://file.lxi.me/uploadify/20160616/57624f695c980.png-scale560\" title=\"QQ截图20160501121853.png\" // 具体描述 alt=\"QQ截图20160501121853.png\"/>+</p><p>+face++</p>", // (string) 描述
                "status": "published", // (string) 状态
                "start_time": 1468239349, // (int) 开始报名时间
                "end_time": 1468239349, // (int) 结束报名时间
                "create_time": 1468239349, // (int) 项目创建时间
                "update_time": 1468464835, // (int) 更新时间
                "sequence": 0, // (int) 排序
                "link": "http://f.lingxi360.com/?token=cNMnkTwiFTamcTwnN" // (string) 链接
              }
            }

## 获取单个表单 [/form/show]

## 获取单个表单 [GET]

| 名称   | 类型 |  必填  |  说明  |
| :-- | :--: | :--: | :-- |
| id  | string | &#10004;  |  表单 id  |

+ Response

```bash
同表单列表
```

## 获取单个表单填表信息列表 [/form/form_fill/list]

## 获取单个表单填表信息列表 [GET]

| 名称   | 类型 |  必填  |  说明  |
| :-- | :--: | :--: | :-- |
| form_id | string |  &#10004;  |  表单 id  |
| order_by | string | &#10007; | `id`, `create_time`, `update_time` |
| with | string | &#10007; | 联系人-`contact` |

+ Response

  + Body


            [
              "type": "form_fill",
              "id": "ca9r4x83g5ep9wn6r9xx6mlo1qyzv27k",
              "attributes": {
                "form_id": "ca7nxo5qvzl9gm1dq2gkd7w3rp24e8yk", // (string)
                "data": { // 填写数据
                  "name": "邓铠易",
                  "mobile": "13720050963",
                  "email": "bupteasy@gmail.com",
                  "new_item_1": "移动互联网"
                },
                "contact_id": "canxv8z25kyqo768gxngm0epgm1rlw94", // 联系人 id
                "create_time": 1403665577,
                "update_time": 0
              },
              "contact": { // 同联系人
                ...
              }
            ]

## 获取单个表单的单个填表信息 [/form/form_fill/show]

## 获取单个表单的单个填表信息 [GET]

| 名称   | 类型 |  必填  |  说明  |
| :-- | :--: | :--: | :-- |
| id | string | &#10004;  |  form_fill id  |
| with | string | &#10007; | 联系人-`contact`, 表单-`form` |

+ Response

```bash
同上
```

# Data Structures

# Group 筹款支付表单

目前灵析筹款表单主要分为 `单次捐`，`组队捐` 和 `定期捐` ，各个类型的表单的项目连接的格式如下：

### 单次捐

* 单次捐筹款

```bash
单次捐筹款的链接格式为： http://cf.lingxi360.com/p/+项目信息哈希

示例：http://cf.lingxi360.com/p/LXEmxB3LG8R0
```

### 组队捐

* 组队捐创建团队

```bash
组队捐创建团队的链接格式为： http://cf.lingxi360.com/p/+项目信息哈希+/up/create

示例： http://cf.lingxi360.com/p/caxpyw3m54kreo8677qg692vnxglzq71/up/create
```

* 组队捐筹款

```bash
组队捐筹款页面的链接格式为： http://cf.lingxi360.com/up/+团队信息哈希（注意和单次捐的区别：中间是 up）

示例：http://cf.lingxi360.com/up/caxpyw3m54kreo8677qg692vnxglzq71
```

### 定期捐

* 定期捐筹款

```bash
定期捐捐赠页面链接格式为： http://cf.lingxi360.com/periodic/+项目信息哈希

示例：http://cf.lingxi360.com/periodic/LXEmxB3LG8R0
```

:::warning
以上项目连接均为展示格式之用，链接所对应项目未必都真实存在
:::

### 获取表单字段 name 值

在浏览器中通过 `开发者工具（推荐）` 或者 `查看源代码` 的方式找到需要操作的表单字段的对应 `name` 值。`name` 值将用来和表单的相关操作通信。
注意：通过查看源码可以发现部分表单的的 `name` 值为 `form_data[*]`，这时的话只需要取 `[]` 中的部分作为传递的 `name` 即可。

### 特殊字段的处理

在获取 `name` 值得时候，有几个字段的 `name`值比较特殊，现在下表说明，调用过程中一定要注意这个部分。

|  序号  |	字段描述	|  字段 name  |  说明  |
| --- | --- | --- |--- |
|  1  |  捐款金额  |  donate_amount  | 捐款金额在不同的页面都有出现，这个字段主要用来设置捐款的金额，因为在页面中比较难发现，特在此指出  |
|  2  |  筹款目标  |  goal  | 筹款目标出现在团队捐团队创建页面，为避免与捐款金额混淆，特在此指出  |
|  3  |  捐赠项目  |  donate_project  | 捐赠项目在页面中有父项目和子项目之分，但是在设置的时候只需设置一个参数 `donate_project` 即可，此字段的值为一个 `int` 类型的 `id` ，此  `id` 可以在灵析后台项目管理页面的第一页找到 |
|  4 |  发票地址字段  |  invoice_address  | 在查看发票部分的源码时，会发现 `发票地址` 有上下两个 `name` 值，在对发票地址进行操作的时候，无需管页面中的两个 `nama` 值，只需设置 `name=invoice_address`  即可|

### [操作] 自动弹出捐赠窗口

此接口能控制在筹款项目页面打开时是否自动弹出捐赠项目的支付弹窗。

```
示例：http://cf.lingxi360.com/p/LXEmxB3LG8R0?_setting_form_popup=1
```

```bash
_setting_form_popup: int (默认 0)

设置为1将在页面打开时自动弹出捐赠表单，目前仅支持移动端的单次捐捐款页面，组队捐捐款页面和定期捐捐款页面
```

### [操作] 设置默认值

可以通过在url参数中设置表单项目的默认值。

```
示例：http://cf.lingxi360.com/p/LXEmxB3LG8R0?_default_title=今天天气很好
```

使用方式的在链接后面传递参数 default_* ，*可以是页面表单中存在的任意 name 值。

```bash
_default_name:	string

_default_*，* 代表页面中存在字段的 name 值
```

### [操作] 属性只读

可以通过在 `url `参数中设置表单字段是否只读。

```
//此时表单中的 title 字段会被设置为不可修改的状态
示例：http://cf.lingxi360.com/p/LXEmxB3LG8R0?_unchangeable_title=1
```

使用方式的在链接后面传递参数 `_unchangeable_*` ，`*`可以是页面表单中存在的任意 `name` 值。

```
string: _unchangeable_name=默认 0 #_unchangeable_*，* 代表页面中存在字段的 name 值
```

:::note
以上几个操作可以同时进行，操作是只需将多个参数使用 `&` 连接起来即可。为保证结果的正确性和 `API` 能被正确执行，在参数传递的时候记得对 `中文` 和 `特殊符号` 进行转义。

```
//多个参数同时使用示例
http://cf.lingxi360.com/p/LXE8G6B_tyG=GOAF?_default_donate_project=50585&_setting_form_popup=1
```
:::

# Data Structures

# Group 错误代码说明

### 签名验证错误

| 错误码 status_code   |  message  |  description  |
| -- | -- | -- |
|10001 | Miss required parameters, see doc for more info | 缺失验证参数，请参考 API 文档 |
|10002 | Timestamp expire | 时间戳过期，请重新发起请求 |
|10003 | Param error, see doc for more info | 验证参数错误，请参考API文档 |
|10004 | Signature not valid... | 签名验证失败 |
|10005 | Api key not exist, please contact lingxi manager. | Api Key 无效，请向灵析申请 |
|10007 | Api request times overload... | API 请求过于频繁，请稍后重试 |
|10009 | Partner key not exist, please contact lingxi manager. | Partner Key 无效，请向灵析申请 |
|10011 | You must be our partner. | 你必须有 partner 级别的账号才能访 |

### 请求获取数据错误

| 错误码 status_code   |  message  |  description  |
| -- | -- | -- |
|20000 | Miss required parameters, see doc for more info | 接口所需参数不全，请参考 API 文档|
|20001 | Contact not exist | 请求的联系人不存在|
|20003 | Parameters not invalid | 好好看文档，看清楚参数说明|
|20005 | Contact\'s Event not exist | 请求的联系人没有参与任何活动|
|20007 | Role not exist in this team. | 没有找到这个身份|
|20009 | There was no donate... | 目前并没有捐款记录|
|20011 | No project you want... | 并没有符合条件的项目存在|
|20013 | No Event you want... | 没有获取到任何活动信息|
|20015 | No donate you want... | 捐款被黑洞吞噬了|
|20017 | Not find any comments. | 没有找到任何留言信息|
|20019 | Not find periodic project you join | 没有绑定任何定期捐|
|20021 | Not find user project | 没有找到团队捐信息|
|20023 | Not progress finded. | 没有任何项目进度信息|
|20025 | Not category finded. | 没有任何分类|
|20045 | Form, Form, Form, Not exist... | 没有获取到任何表单|
|20047 | Cms Category Not exist... | 没有找到一个分类信息|
|20047 | Cms Config not exist. | 没有获取到配置信息|
|20049 | Cms content not exist. | 没有获取到内容信息|
|20051 | Cms Banner not exist. | 没有获取到 Banner 信息|
|20052 | Cms tag not exist. | 没有获取到标签信息|
|20053 | Nobody take part in this event | 没有获取到任何活动参与信息|
|20095 | Please config you wechat app id and secret | 赶紧去配置你的微信app id 和 secret|
|20095 | Not found model | 没有查询到数据|
|20097 | Some quert error | 亲爱的开发者，请仔细传递参数|
|20099 | Throw a error when parse your parameters | 参数解析错误|

### 其他

| 错误码 status_code   |  message  |  description  |
| -- | -- | -- |
| 99999 | Not known error | 未知错误，请联系我们 |
